name: Build

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 5 * * 1" # Every Monday morning

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build
      cancel-in-progress: true
    env:
      REGISTRY: ghcr.io
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
      REPO: jdobes/caddy
      PLATFORM: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install qemu-user-static for multi-arch build
        run: |
          sudo apt update && sudo apt install -y qemu-user-static
      - name: Login to registry
        run: |
          echo "$REGISTRY_PASS" | podman login -u "$REGISTRY_USER" --password-stdin "$REGISTRY"
      - name: Build and push latest version
        run: |
          LATEST_UPSTREAM_VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r '.tag_name' | sed 's/v//')
          LATEST_REBUILT_VERSION=$(curl -s -H "Authorization: Bearer $REGISTRY_PASS" https://api.github.com/users/jdobes/packages/container/caddy/versions | jq -r 'sort_by(.id) | reverse | .[0].metadata.container.tags.[] | select(. != "latest")')
          echo "LATEST_UPSTREAM_VERSION: $LATEST_UPSTREAM_VERSION"
          echo "LATEST_REBUILT_VERSION: $LATEST_REBUILT_VERSION"
          if [ "$LATEST_UPSTREAM_VERSION" != "$LATEST_REBUILT_VERSION" ]; then
              podman build --platform "$PLATFORM" --manifest caddy --build-arg CADDY_VERSION=$LATEST_UPSTREAM_VERSION .
              podman manifest push caddy docker://$REGISTRY/$REPO:$LATEST_UPSTREAM_VERSION
              podman manifest push caddy docker://$REGISTRY/$REPO:latest
              podman manifest rm caddy
          else
              echo "Build skipped."
          fi
